language: "en"

# "tensorflow_embedding"
pipeline: "tensorflow_embedding"
# - name: "tokenizer_whitespace"
# - name: "slang.SlangReplace"
# - name: "spell.SpellingCorrect"
# - name: "nlp.Lemmatizer"
# - name: "vectorizer.WordVectorizer"
# - name: "intentClassifier.CNN"

#pipeline: name#
# - name: "tokenizer_whitespace"
# - name: "tokenizer_whitespace"
#- name: "intent_entity_featurizer_regex"
#- name: "ner_crf"
#- name: "ner_synonyms"
#- name: "intent_featurizer_count_vectors"
#- name: "intent_classifier_tensorflow_embedding"